# Generated by Django 5.1.4 on 2024-12-19 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('rank', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('conference_name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('is_institution', models.BooleanField(default=False)),
                ('formal_version', models.CharField(blank=True, max_length=255, null=True)),
                ('chinese_name', models.CharField(blank=True, max_length=255, null=True)),
                ('related_university', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaperAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_first_author', models.BooleanField(default=False)),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.author')),
                ('paper_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.paper')),
            ],
            options={
                'unique_together': {('paper_title', 'author_name')},
            },
        ),
        migrations.CreateModel(
            name='AuthorUniversity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.author')),
                ('university_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rankings.university')),
            ],
            options={
                'unique_together': {('author_name', 'university_name')},
            },
        ),
    ]
